### ISSUE TITLE
LR Finder for RNN network

### ISSUE THREAD

**Issue by PariksheetPinjari909** [davidtvs/pytorch-lr-finder#12]
Hi,

I want to find lr for my RNN network which will have sequence as an input. When i try with torch_lr_finder it throws error as 

```
File "/usr/local/lib/python3.5/dist-packages/torch_lr_finder/lr_finder.py", line 125, in range_test
    inputs, labels = next(iterator)
ValueError: too many values to unpack (expected 2)
```

Can you help me to get over this error
@davidtvs

**Comment by NaleRaphael** [comment]
Hi @PariksheetPinjari909 ,

It seems like there are multiple values without being packed in a single data sample, so that it resulted this error while unpacking. Could you try to get the information of the shape of each object in a data sample?
e.g. `print([v.shape for v in iter(trainloader).__next__())]`, and the correct result should be a list with length of 2. If it isn't, you may need to make a wrapper to pack the input data and labels to this format `(inputs, labels)`.



Beside, if you are working on a NLP task and going to feed multiple embeddings as a single sample (e.g. sentence), you might need to use this helper function [`pack_padded_sequence`](https://pytorch.org/docs/stable/nn.html?highlight=packedsequence#torch.nn.utils.rnn.pack_padded_sequence).

Please feel free to let me know if there is still any problem!

**Comment by PariksheetPinjari909** [comment]
@NaleRaphael Yes you are correct. My dataset loader have three arguments. It worked after making changes to lr_finder.py. Thanks anyway.

**Comment by PariksheetPinjari909** [comment]
Closing the issue
