### ISSUE TITLE
ERROR: torchvision 0.4.2 has requirement torch==1.3.1, but you'll have torch 1.2.0 which is incompatible.

### ISSUE THREAD

**Issue by vpapaioannou** [davidtvs/pytorch-lr-finder#17]
Executing in Google Colab the command,

`!pip install https://download.pytorch.org/whl/cu100/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl && pip install https://download.pytorch.org/whl/cu100/torchvision-0.4.0-cp36-cp36m-manylinux1_x86_64.whl`

found in https://colab.research.google.com/drive/1BhWYtLFOa24wisNckt9i6rQhBKurVWWV

gives the error

ERROR: torchvision 0.4.2 has requirement torch==1.3.1, but you'll have torch 1.2.0 which is incompatible..

By the way, executing `!cat /usr/local/cuda/version.txt` gives
CUDA Version 10.0.130

Please advise.

Thanks,

Vassilis

**Comment by davidtvs** [comment]
The error is shown because the first command installs an incompatible version of pytorch but then the second command will fix that. So everything should be fine after the whole cell runs.

FYI, you can replace the command
`pip install https://download.pytorch.org/whl/cu100/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl && pip install https://download.pytorch.org/whl/cu100/torchvision-0.4.0-cp36-cp36m-manylinux1_x86_64.whl`
with 
`pip install torch==1.2.0 torchvision==0.4.0`
has the same end-result and the error won't show up.

**Comment by vpapaioannou** [comment]
Thanks.
