### ISSUE TITLE
Support pytorch's native amp

### ISSUE THREAD

**Issue by daniel-j-h** [davidtvs/pytorch-lr-finder#67]
Hey hey :wave: 

PyTorch now has it's native amp module for a while now

https://pytorch.org/docs/stable/amp.html

it would be great to move to that, or at least prefer using it if it's available.

**Comment by NaleRaphael** [comment]
Yeah, thanks for letting us know about this!

We had noticed that `apex` was going to be supported in PyTorch natively since v1.5, but didn't pay too much attention on its progress. But it seems `torch.cuda.amp` is stable enough now. I'll submit a new PR for it. 🤘

**Comment by daniel-j-h** [comment]
Awesome, this was quick 🎉 🤗

**Comment by NaleRaphael** [comment]
Hey @daniel-j-h,

I would like to let you know that I have been busy with other things these weeks, so that the PR would be submitted lately.
I've reviewed the difference between the implementation of `apex.amp` and `torch.cuda.amp` (v1.4 ~ v1.7) a few weeks ago, and some sketches of the changes to lr-finder had been done. But there are additional tests should be done to make sure it works for both `apex.amp` and `torch.cuda.amp`, hence that I have to take more time on it.

I'm sorry for any inconvenience resulted by this delay. I'll update this thread when the PR is ready.
But if you have any further questions, please feel free to let me know. I might be free for answering them within a short time.

**Comment by daniel-j-h** [comment]
All good, I think this is important but not urgent :hugs: Thank you for your transparency here! :bow:

**Comment by carbocation** [comment]
From what I can tell in the documentation, apex is still needed to take advantage of AMP with this library. Is that the case or is this issue completed?

**Comment by davidtvs** [comment]
Closing, I believe https://github.com/davidtvs/pytorch-lr-finder/pull/91 addressed this issue
