### ISSUE TITLE
TypeError: cannot unpack non-iterable AxesSubplot object

### ISSUE THREAD

**Issue by laiyuzhi** [davidtvs/pytorch-lr-finder#88]
Axes, bestlr = lr_finder.plot(ax=ax, suggest_lr=True)
TypeError: cannot unpack non-iterable AxesSubplot object

Sometimes this error happens to me, is there a solution?

**Comment by NaleRaphael** [comment]
Hi @laiyuzhi,
it seems there is no sufficient data points (`num_iter` < 17 for `range_test()`) for `lr_finder` to calculate gradient as `min_grad_idx`, so that `lr_finder.plot()` returns only the `AxesSubplot` object.

This is a thing that we need to fix since the output should be expected as two values when `suggest_lr` is set to True.

Before the patch is submitted, you could try the following approaches to avoid this situation:
1. make sure `num_iter` always >= 17 (`skip_start=10`, `skip_end=5`, and there should be at least 2 points for `np.gradient()`)
2. set both `skip_start` and `skip_end` to 0 (but you still need to make sure `num_iter` >= 2)

Or you can apply this patch temporarily:
```diff
diff --git a/torch_lr_finder/lr_finder.py b/torch_lr_finder/lr_finder.py
index 8311bf5..e60f2cd 100644
--- a/torch_lr_finder/lr_finder.py
+++ b/torch_lr_finder/lr_finder.py
@@ -532,8 +532,10 @@ class LRFinder(object):
         if fig is not None:
             plt.show()
 
-        if suggest_lr and min_grad_idx is not None:
-            return ax, lrs[min_grad_idx]
+        suggested_lr = lrs[min_grad_idx] if min_grad_idx is not None else None
+
+        if suggest_lr:
+            return ax, suggested_lr
         else:
             return ax
```

But please note using a low `num_iter` might not be sufficient to get a proper lr-loss curve for suggested learning rate. And the patch above would still return a `None` value for suggested learning rate, you need to check whether it's a numerical value before doing further operation on it.
