### ISSUE TITLE
How is this supposed to work?

### ISSUE THREAD

**Issue by qudabear** [davidtvs/pytorch-lr-finder#96]
A description of what it does, but no instructions on how to install or use it? No install scripts? How am I supposed to get this working on Mac OSX? I've managed to manually "install", but how can I run it? Where are the lists of commands? How can I run this on my own custom dataset?

**Comment by davidtvs** [comment]
The README does have a section about [Installation](https://github.com/davidtvs/pytorch-lr-finder?tab=readme-ov-file#installation) and right below it [Implementation details and usage](https://github.com/davidtvs/pytorch-lr-finder?tab=readme-ov-file#implementation-details-and-usage). There's also a bunch of examples in the [examples](https://github.com/davidtvs/pytorch-lr-finder/tree/master/examples) folder.

There are no commands, this is not a CLI tool, it's a Python package that you have to integrate with your own code so that you can use it with your model and dataset.
